### ISSUE TITLE
Galeria de Imagens de Imóvel

### ISSUE THREAD

**Issue by IgorMarques** [4Soft/iglesiasapi#12]
Lista de fotos de um imóvel, de preferência em outra tela.

Cada foto possui uma legenda.

Seleção de "foto de destaque"

Descrição do cliente:

"      - sugestão: incluir um símbolo para fotos do imóvel,
                          quando clicar nele, será mostrado uma página de manutenção das fotos deste imóvel:
                          - listar todas as fotos cadastradas, botão para excluir uma existente, botão para a foto ser mostrada em destaque na
                            página principal do site, campo para escrever texto comentário de cada foto,
                            botão para inserir nova foto,
"

**Comment by lucasbibiano** [comment]
> Verificar se a seleção de imagem principal funciona no Heroku (Imóveis > Editar Imóvel PN3C)

nao saquei

**Comment by IgorMarques** [comment]
Tenta selecionar uma imagem la e ve se ela fica marcada como capa de fato (no heroku). Ela tinha dito que nao tava conseguindo fazer isso.

**Comment by lucasbibiano** [comment]
Ta rolando sim, soh não ta atualizando automaticamente

**Comment by IgorMarques** [comment]
como assim? Recarregar a página? Se for esse o carro, manda dar um refresh automatico

**Comment by lucasbibiano** [comment]
Eh o que eu vou fazer, mas lembro que já tinha feito. Deve ter rolado alguma treta

**Comment by bernardogfilho** [comment]
Recentemente eu vi esse projeto bem legal:
https://github.com/dimsemenov/PhotoSwipe

**Comment by IgorMarques** [comment]
Parece ser muito bem feitinha. Dps dá uma conferida, @lucasbibiano
